### ISSUE TITLE
Why does NFID connect to AWS?

### ISSUE THREAD

**Issue by vporton** [internet-identity-labs/sdk#39]
Apparently, NFID was hacked, because it tries to connect to AWS, what should not happen!

As I see from browser logs:

`Uncaught (in promise) Aborted webauthn on unmount in browser logs.`
It asks AWS to sign ECDSA https://28oge2ricd.execute-api.us-east-1.amazonaws.com/prod/ecdsa_sign
Error 400 is returned with `{}` body.
`Uncaught (in promise) {error: 'The delegation cannot be obtained: {}'}`
Note that nfid.getDelegation async function never finishes, as seen from no `delegationIdentity` in browser logs.

Here is the code:
```typescript
      const nfid = await NFID.init({
        application: {
          name: "Zon",
          // logo: "https://dev.nfid.one/static/media/id.300eb72f3335b50f5653a7d6ad5467b3.svg" // TODO
        },
      });
      const delegationIdentity: Identity = await nfid.getDelegation({
        // optional targets ICRC-28 implementation, but required to support universal NFID Wallet auth
        targets: [], // FIXME: needed?
        // optional derivationOrigin in case you're running on a custom domain
        derivationOrigin: `https://${process.env.CANISTER_ID_frontend!}.icp0.app`,
        // optional maxTimeToLive defaults to 8 hours in nanoseconds;
        maxTimeToLive: BigInt(8) * BigInt(3_600_000_000_000) // TODO
      });
      console.log("delegationIdentity", delegationIdentity);
      updateClientNfid(delegationIdentity);
...
```

* Run the above code in a browser.
* Watch for no `delegationIdentity`, but errors in the browser log.
* Scroll down to '....'
* See error

Expected behavior
* The delegation identity to be returned, with no error messages.

Desktop (please complete the following information):
- OS: Ubuntu 23.04
- Browser Chromium 117.0.5938.92 snap
- Version `@nfid/embed ^0.10.0-alpha.1`

It also returns `X-Cache: Error from cloudfront` in the response to `/ecdsa_sign`.

Here is a fragment of compiled code:
```javascript
            async function p(e, t, r) {
                const n = await y(r)
                  , o = await v(t, n, new Date(Date.now() + 10 * i.FZ), {
                    previous: t.getDelegation()
                })
                  , a = {
                    chain: r,
                    delegationChain: JSON.stringify(o.toJSON()),
                    tempPublicKey: n,
                    keccak: e
                }
                  , u = s.ic.isLocal ? "/ecdsa_sign" : "https://28oge2ricd.execute-api.us-east-1.amazonaws.com/prod/ecdsa_sign";
                return await fetch(u, {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify(a)
                }).then((async e=>{
                    if (!e.ok)
                        throw new Error(await e.text());
                    return await e.json()
                }
                ))
            }
```
Links to aws were found in https://nfid.one/static/js/main.ecca3531.js

What the hell aws URLs in this code meant to be decentralized?

And what was this code generated from? We have no `aws` queries in the sources! So, it apparently was hacked.

**Comment by vporton** [comment]
You have a security failure. And you still didn't respond to it for more than 4 days!

Well, the file https://nfid.one/static/js/main.ecca3531.js was deleted, but where is a new release that fixes the bug?!

**Comment by vporton** [comment]
You claimed that the issue was fixed in `@nfid/embed ^0.10.0-alpha.1`, but it wasn't. Now there is `0.10.0-alpha.6`.

Was the issue fixed or no?

**Comment by vporton** [comment]
`0.10.0-alpha.6` still does

POST https://28oge2ricd.execute-api.us-east-1.amazonaws.com/prod/ecdsa_sign

Fix the bug!!

**Comment by vporton** [comment]
Note that this POST is now called from https://nfid.one/static/js/main.aad97c64.js

**Comment by vporton** [comment]
The "infected" file https://nfid.one/static/js/main.aad97c64.js is still not deleted. Shame on your team of having not fixed or even adequately responded on this malware or malware-like thing.

**Comment by dostro** [comment]
For the sake of completeness in this repo, I'm pasting what I responded in [Discord](https://discord.com/channels/885612184246288414/956614110404030464/1166744157147107409) on 10/25/2023:

> It's important to understand that the Internet Computer is still in the process of becoming secure enough to handle application-level secrets and fast enough to support consumer applications like NFID Wallet. To address this, we've taken steps to offload certain high-security requests, such as emails, magic links, and Google OAuth, to a high-trust environment. This move is essential to support email authentication while preventing the kinds of attacks we've been observing.

**Comment by vporton** [comment]
> to a high-trust environment

@dostro Do you mean AWS as the high-trust environment? It does not work: AWS returns HTTP errors, when I try to login into my app based on NFID.

Something is wrong and I ask you to explain it.
